apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-nodejs
  labels:
    app: gitops-demo-nodejs
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitops-demo-nodejs
    spec:
      containers:
      - image: brentley/ecsdemo-nodejs:latest
        imagePullPolicy: Always
        name: gitops-demo-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP
