apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-nodejs
spec:
  selector:
    app: gitops-demo-nodejs
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
